//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.26 at 05:29:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema
(	namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2",
	xmlns = @XmlNs(prefix = "p", namespaceURI = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2"))
package biz.opengate.fatturaelettronica;

import javax.xml.bind.annotation.XmlNs;