//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.27 at 04:50:47 PM CET 
//


package biz.opengate.fatturaelettronica.messaggi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RiferimentoFattura_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RiferimentoFattura_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroFattura" type="{http://www.fatturapa.gov.it/sdi/messaggi/v1.0}NumeroFattura_Type"/>
 *         &lt;element name="AnnoFattura" type="{http://www.fatturapa.gov.it/sdi/messaggi/v1.0}AnnoFattura_Type"/>
 *         &lt;element name="PosizioneFattura" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RiferimentoFattura_Type", namespace = "http://www.fatturapa.gov.it/sdi/messaggi/v1.0", propOrder = {
    "numeroFattura",
    "annoFattura",
    "posizioneFattura"
})
public class RiferimentoFatturaType {

    @XmlElement(name = "NumeroFattura", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numeroFattura;
    @XmlElement(name = "AnnoFattura", required = true)
    protected BigInteger annoFattura;
    @XmlElement(name = "PosizioneFattura")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger posizioneFattura;

    /**
     * Gets the value of the numeroFattura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFattura() {
        return numeroFattura;
    }

    /**
     * Sets the value of the numeroFattura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFattura(String value) {
        this.numeroFattura = value;
    }

    /**
     * Gets the value of the annoFattura property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnnoFattura() {
        return annoFattura;
    }

    /**
     * Sets the value of the annoFattura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnnoFattura(BigInteger value) {
        this.annoFattura = value;
    }

    /**
     * Gets the value of the posizioneFattura property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosizioneFattura() {
        return posizioneFattura;
    }

    /**
     * Sets the value of the posizioneFattura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosizioneFattura(BigInteger value) {
        this.posizioneFattura = value;
    }

}
