//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.27 at 04:50:47 PM CET 
//


package biz.opengate.fatturaelettronica.messaggi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Scarto_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Scarto_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EN00"/>
 *     &lt;enumeration value="EN01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Scarto_Type", namespace = "http://www.fatturapa.gov.it/sdi/messaggi/v1.0")
@XmlEnum
public enum ScartoType {


    /**
     * 
     * 						EN00 = NOTIFICA NON CONFORME AL FORMATO
     * 					
     * 
     */
    @XmlEnumValue("EN00")
    EN_00("EN00"),

    /**
     * 
     * 						EN01 = NOTIFICA NON AMMISSIBILE
     * 					
     * 
     */
    @XmlEnumValue("EN01")
    EN_01("EN01");
    private final String value;

    ScartoType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScartoType fromValue(String v) {
        for (ScartoType c: ScartoType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
